name: PhantomSMP
version: 1.0.0
main: com.minetwice.phantomsmp.PhantomSMP
api-version: 1.21
author: MineTwice
description: 30 Unique Power Books System for SMP

commands:
  smpstart:
    description: Start the SMP and distribute power books
    usage: /smpstart
    permission: phantomsmp.admin
  smprewind:
    description: Remove all power books from players
    usage: /smprewind
    permission: phantomsmp.admin
  books:
    description: Open power books menu
    usage: /books
    permission: phantomsmp.admin
  bookgive:
    description: Give a specific power book to a player
    usage: /bookgive <player> <book>
    permission: phantomsmp.admin
  trade:
    description: Trade power books with another player
    usage: /trade <player>
    permission: phantomsmp.player

permissions:
  phantomsmp.admin:
    description: Admin permissions
    default: op
  phantomsmp.player:
    description: Player permissions
    default: true
